"""sparton unified schema

Revision ID: f4d75c8de498
Revises: 
Create Date: 2026-08-25 21:26:16.456393
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision: str = 'f4d75c8de498'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
